name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
        - [linux, ubuntu-latest]
        - [darwin, macos-latest]

    runs-on: ${{matrix.platform[1]}}

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: 'Build Node with corepack master'
      run: |
        yarn install --immutable
        yarn pack
        git clone -b mael/pmm --depth=1 https://github.com/arcanis/node.git node && cd node
        git config user.name 'John Doe'
        git config user.email 'john@example.org'
        rm -rf deps/corepack && tar xvf ../package.tgz && mv package deps/corepack
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Updates corepack'
          git show --name-status
        fi
        ./configure
        DISTTYPE=nightly DATESTRING=YYYY-MM-DD COMMIT=XXXX make binary -j8
        mv node-v15.0.0-nightlyYYYY-MM-DDXXXX-*.tar.gz node-corepack-${{matrix.platform[0]}}-x64.tar.gz

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: node-corepack-${{matrix.platform[0]}}-x64
        path: node/node-corepack-${{matrix.platform[0]}}-x64.tar.gz
