name: Version Sync

on:
  workflow_dispatch:
  schedule:
    # Run once a week at 00:05 UTC on Sunday.
    - cron: 5 0 * * 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: "Update the package manager versions"
        run: |
          LATEST_NPM=$(curl https://registry.npmjs.org/npm | jq '.["dist-tags"].latest')
          LATEST_PNPM=$(curl https://registry.npmjs.org/pnpm | jq '.["dist-tags"].latest')
          LATEST_YARN=$(curl https://registry.npmjs.org/yarn | jq '.["dist-tags"].latest')
          LATEST_BERRY=$(curl https://repo.yarnpkg.com/tags | jq '.latest.stable')

          git --no-pager show HEAD:config.json | jq '. * '"{
            definitions: {
              npm: {
                default: $LATEST_NPM,
              },
              pnpm: {
                default: $LATEST_PNPM,
              },
              yarn: {
                default: $LATEST_YARN,
                transparent: {
                  default: $LATEST_BERRY,
                },
              },
            },
          }" > config.json

      - uses: gr2m/create-or-update-pull-request-action@6720400cad8e74d7adc64640e4e6ea6748b83d8f
        # Creates a PR or update the Action's existing PR, or
        # no-op if the base branch is already up-to-date.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: This is an automated update of package manager versions
          branch: actions/tools-update-config.json
          commit-message: "chore: update package manager versions"
          title: "chore: update package manager versions"
